""" Initial Migration 

Revision ID: 5dcc25a78b5a
Revises: 
Create Date: 2023-12-11 18:40:05.354358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcc25a78b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_decks_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_operation', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_subjects_question_id_questions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('card_deck_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_deck_id'], ['card_decks.id'], name=op.f('fk_question_cards_card_deck_id_card_decks')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_cards_question_id_questions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_card_id'], ['question_cards.id'], name=op.f('fk_answers_question_card_id_question_cards')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_answers_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('question_cards')
    op.drop_table('subjects')
    op.drop_table('card_decks')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
